#Mongo
quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}
quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin

#Logs
quarkus.log.category."org.mongodb.driver".level=WARN

#External services
ebi-api/mp-rest/url=https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms
ncbi-api/mp-rest/url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils

# RabbitMQ conection
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=admin
rabbitmq-password=password123

# Producer channel configuration
mp.messaging.outgoing.ncbi-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ncbi-out.exchange.name=exchange-ncbi

# Consumer channel configuration
mp.messaging.incoming.ncbi-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ncbi-in.queue.name=queue-ncbi
